import React from 'react';

const About = () => {
  return (
    <div id="about" className='w-full bg-[#ffffff] py-10 md:py-20'> {/* Adjust padding for different screen sizes */}
        <div className='mx-auto px-4 max-w-xs sm:max-w-lg md:max-w-2xl lg:max-w-[1480px]'> {/* Responsive max-width */}
            <h1 className='text-center text-5xl font-bold text-black mb-6'>About Me</h1>
            <p className='text-center text-[#ee7600] text-base md:text-xl mb-8'>From Classroom to Code</p>
            <p className='text-center text-[#ee7600] font-bold text-base md:text-xl mb-8'>An Aspiring Software Developer from SF State Seeking to Shape the Future with AI and Problem-Solving Skills</p>
            <div className='flex flex-wrap justify-center gap-4 md:gap-8'> {/* Use flex-wrap for responsive image layout */}
              <img src="./tennis.jpg" alt="Tennis" className='icon w-20 h-20 md:w-24 md:h-24' />
              <img src="./tea.jpg" alt="Tea" className='icon w-20 h-20 md:w-24 md:h-24' />
              <img src="./code.jpg" alt="Code" className='icon w-20 h-20 md:w-24 md:h-24' />
              <img src="./music.jpg" alt="Music" className='icon w-20 h-20 md:w-24 md:h-24' />
              <img src="./gym.jpg" alt="Gym" className='icon w-20 h-20 md:w-24 md:h-24' />
            </div>
            <p className='text-center text-[#536E96] text-xs mt-8'>Images Generated by ChatGPT</p>
        </div>
    </div>
  )
}

export default About;
